FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

ENV MOCK_URL=http://mock-comtrade:8000
ENV PURPLE_OUTPUT_ROOT=/workspace/purple_output
ENV PORT=9009

CMD ["python","-m","src.agent"]
