FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY mock_service /app/mock_service

CMD ["uvicorn","mock_service.app:app","--host","0.0.0.0","--port","8000"]
